version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "lockfile-only"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "auto-approve"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
    labels:
      - "auto-approve"
